spring.application.name=geographic-games-service

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:geographic}
spring.datasource.username=${DB_USER:geographic}
spring.datasource.password=${DB_PASSWORD:geographic}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
