### Send create daily entry POST request
POST http://localhost:8080/api/daily-entries
Content-Type: application/json

{
  "game": {
    "id" : 1,
    "name": "TestGame1"
  },
  "player": {
    "id" : 1,
    "name": "Testplayer"
  },
  "date": "2026-08-17",
  "points" : 568
}

### Send get daily ranking GET request
GET http://localhost:8080/api/daily-ranking?date=2026-08-17
